/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppInvitationsRouteImport } from './routes/_app/invitations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppTenantsIndexRouteImport } from './routes/_app/tenants/index'
import { Route as AppTenantsTenantIdWorkspaceRouteImport } from './routes/_app/tenants/$tenantId/workspace'
import { Route as AppTenantsTenantIdSettingsRouteImport } from './routes/_app/tenants/$tenantId/settings'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsRoute = AppInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsIndexRoute = AppTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsTenantIdWorkspaceRoute =
  AppTenantsTenantIdWorkspaceRouteImport.update({
    id: '/tenants/$tenantId/workspace',
    path: '/tenants/$tenantId/workspace',
    getParentRoute: () => AppRoute,
  } as any)
const AppTenantsTenantIdSettingsRoute =
  AppTenantsTenantIdSettingsRouteImport.update({
    id: '/tenants/$tenantId/settings',
    path: '/tenants/$tenantId/settings',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/invitations': typeof AppInvitationsRoute
  '/profile': typeof AppProfileRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/tenants/': typeof AppTenantsIndexRoute
  '/tenants/$tenantId/settings': typeof AppTenantsTenantIdSettingsRoute
  '/tenants/$tenantId/workspace': typeof AppTenantsTenantIdWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/invitations': typeof AppInvitationsRoute
  '/profile': typeof AppProfileRoute
  '/subscription': typeof AppSubscriptionRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/tenants': typeof AppTenantsIndexRoute
  '/tenants/$tenantId/settings': typeof AppTenantsTenantIdSettingsRoute
  '/tenants/$tenantId/workspace': typeof AppTenantsTenantIdWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/invitations': typeof AppInvitationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/tenants/': typeof AppTenantsIndexRoute
  '/_app/tenants/$tenantId/settings': typeof AppTenantsTenantIdSettingsRoute
  '/_app/tenants/$tenantId/workspace': typeof AppTenantsTenantIdWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invitations'
    | '/profile'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/tenants/'
    | '/tenants/$tenantId/settings'
    | '/tenants/$tenantId/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/invitations'
    | '/profile'
    | '/subscription'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/tenants'
    | '/tenants/$tenantId/settings'
    | '/tenants/$tenantId/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/invitations'
    | '/_app/profile'
    | '/_app/subscription'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/tenants/'
    | '/_app/tenants/$tenantId/settings'
    | '/_app/tenants/$tenantId/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invitations': {
      id: '/_app/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AppInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/': {
      id: '/_app/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AppTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/$tenantId/workspace': {
      id: '/_app/tenants/$tenantId/workspace'
      path: '/tenants/$tenantId/workspace'
      fullPath: '/tenants/$tenantId/workspace'
      preLoaderRoute: typeof AppTenantsTenantIdWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/$tenantId/settings': {
      id: '/_app/tenants/$tenantId/settings'
      path: '/tenants/$tenantId/settings'
      fullPath: '/tenants/$tenantId/settings'
      preLoaderRoute: typeof AppTenantsTenantIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvitationsRoute: typeof AppInvitationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTenantsIndexRoute: typeof AppTenantsIndexRoute
  AppTenantsTenantIdSettingsRoute: typeof AppTenantsTenantIdSettingsRoute
  AppTenantsTenantIdWorkspaceRoute: typeof AppTenantsTenantIdWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInvitationsRoute: AppInvitationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTenantsIndexRoute: AppTenantsIndexRoute,
  AppTenantsTenantIdSettingsRoute: AppTenantsTenantIdSettingsRoute,
  AppTenantsTenantIdWorkspaceRoute: AppTenantsTenantIdWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
